### ISSUE TITLE
1.19 Errors when creating Portals

### ISSUE THREAD

**Issue by Juicy00** [FentisDev/PortalGun#4]
Hiya, currently using the latest version on an up to date Spigot server. This is without any other plugins or resource packs. Seems to be spitting out errors whenever I try to create a portal. The server logs also mention the NBTAPI being out of date. I take that the message about nagging the mod author might have something to do with the errors.

Thanks for the mod, it's been a lot of fun (when it was working lol). Looking forward to seeing this fixed, have a great day.

```
[12:21:36 WARN]: [NBTAPI] The NBT-API located at 'package de.tr7zw.portalgun.nbtapi' seems to be outdated!
[12:21:36 WARN]: [NBTAPI] Current Version: '2.10.0-SNAPSHOT' Newest Version: 2.10.0'
[12:21:36 WARN]: [NBTAPI] Please update the NBTAPI or the plugin that contains the api(nag the mod author when the newest release has an old version, not the NBTAPI dev)!
```

```
[12:22:51 ERROR]: Could not pass event PlayerInteractEvent to PortalGun v1.0.4-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:505) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:472) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:468) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1638) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3527-Spigot-56be6a8-8fda4b1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at pl.by.fentisdev.portalgun.listeners.PortalListeners.onClickPortalGun(PortalListeners.java:143) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 23 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.map.MapView.getRenderers()" because "mapView" is null
	at pl.by.fentisdev.portalgun.utils.PortalUtils.createPortalMapItem(PortalUtils.java:117) ~[?:?]
	at pl.by.fentisdev.portalgun.utils.PortalUtils.<init>(PortalUtils.java:50) ~[?:?]
	at pl.by.fentisdev.portalgun.utils.PortalUtils.<clinit>(PortalUtils.java:27) ~[?:?]
	at pl.by.fentisdev.portalgun.listeners.PortalListeners.onClickPortalGun(PortalListeners.java:143) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by FentisDev** [comment]
Hi! Regarding the NBT API I ended up forgetting to change from the dev version to the public one, but don't worry, this shouldn't cause any problems.
From what I can see you are having problems rendering the maps that are used to make the portal appear, I don't know what happened for this to occur but this can happen if you delete your map without resetting the config.yml of the plugin portals.
Please try this possible solution:
Reset the PortalMapID in the plugin's config.yml putting all values to -1
Please let me know if it worked.
Thanks for the report I think I can work on something so that this doesn't happen in the future.

```
PortalMapID:
  blue:
    up: -1
    down: -1
  orange:
    up: -1
    down: -1
  aqua:
    up: -1
    down: -1
  red:
    up: -1
    down: -1
  yellow:
    up: -1
    down: -1
  purple:
    up: -1
    down: -1
```

**Comment by Juicy00** [comment]
Just attempted it and yes it did work. Didn't change anything else whilst implementing that fix btw, so I can definitely confirm that that fixed it. Thanks!

**Comment by FentisDev** [comment]
Excellent! Thanks again for the report!
